export const EXTRACT_CONFIG = {
  MAX_BYTES: 10 * 1024 * 1024,
  SMALL_UPLOAD_MAX_BYTES: 4 * 1024 * 1024,
  TEXT_PAGE_THRESHOLD_CHARS: 300,
  TOKEN_BUDGET: Number(process.env.EXTRACT_TOKEN_BUDGET ?? 8000),
  MAX_PAGES: Number(process.env.EXTRACT_MAX_PAGES ?? 20),
  MAX_IMAGES: Number(process.env.EXTRACT_MAX_IMAGES ?? 10),
  SCHEMA_VERSION: "2.0.0",
};


